version: '3.8'

services:
  chat-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - ./:/app
    stdin_open: true
    tty: true 