# Сценарий 1: Один бэкэнд + балансировщик, локальная память, нет Redis
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/scenario-1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
    restart: unless-stopped

  backend1:
    build: .
    environment:
      - BACKEND_ID=1
      - USE_REDIS=false
      - PORT=5000
    expose:
      - "5000"
    restart: unless-stopped 