# Сценарий 5: Два бэкэнда + балансировка по chat_id + Redis  
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/scenario-5.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    restart: unless-stopped

  backend1:
    build: .
    environment:
      - BACKEND_ID=1
      - USE_REDIS=true
      - REDIS_HOST=redis
      - PORT=5000
    expose:
      - "5000"
    depends_on:
      - redis
    restart: unless-stopped

  backend2:
    build: .
    environment:
      - BACKEND_ID=2
      - USE_REDIS=true
      - REDIS_HOST=redis
      - PORT=5000
    expose:
      - "5000"
    depends_on:
      - redis
    restart: unless-stopped 